name: CI/CD Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Greetings
      - run: echo "Hello welcome to github!"

      - name: Run command
      - run: pwd

      - name: Deploy
      - run: echo "Deployed successfully!
        "
          
